version: '3.8'

services:
  postgres:
    image: postgres
    container_name: exemplo-next-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - exemplo-next-network

networks:
  exemplo-next-network:

volumes:
  exemplo-next-volume:
